### ISSUE TITLE
Decimal recognized as value

### ISSUE THREAD

**Issue by AdieOlami** [marinofelipe/CurrencyText#70]
## What problems I want to solve?
Awesome Library
The decimal place is recognized as values e.g

1,200.00 is interpreted as 120000 which is wrong. Can there be a fix to this please

**Comment by marinofelipe** [comment]
Hi @AdieOlami , thanks for the report and glad that you like it :)
Sorry for taking so long to answer. 

What is the configuration of the formatter when this error happens? Can you check if `hasDecimals` isn't defined as `false`? It must be set as `true`, which is the default for it.

In case it isn't, can you please share more details around the problem you're facing? 
e.g. the setup of both formatter and delegate, and more details on how it happens. 

Thanks!

**Comment by marinofelipe** [comment]
Hi @AdieOlami, again, sorry for taking so long to answer you here. Are you still facing any issues?

**Comment by marinofelipe** [comment]
Hello @AdieOlami, I'll close this issue due to inactivity, but feel free to open new ones in case you have any questions or problems. Thanks!
