### ISSUE TITLE
Investigate support for SwiftUI

### ISSUE THREAD

**Issue by marinofelipe** [marinofelipe/CurrencyText#72]
## What problems I want to solve?
The functionality provided by CurrencyText should be available not only on UIKit, but also on SwiftUI.

I imagine `CurrencyFormatter` can still be used, but a separate library must be created to support using a currency formatter along with SwiftUI's TextField.

**Comment by tariq235** [comment]
Any update on this ? Really want CurrencyTextField for SwiftUI

**Comment by marinofelipe** [comment]
Hey @tariq235 👋 , no update yet.
I'll get some time this week to finish my investigations, define a plan and start to work on it.

**Comment by marinofelipe** [comment]
Hey I hasn't able to focus on it as I wanted the past week. 
If anyone already has deeper experience with SwiftUI and want to contribute with ideas on how we can support it on CurrencyText, that would be appreciated :).
I'll most likely only be able to put enough hours into evaluating ways of bringing CurrencyText features to SwiftUI next week or so.

**Comment by marinofelipe** [comment]
Investigation was done, now moving to the implementation part, #76.

Basically the decision was between two main options, by priority:
**1.** Vanilla `SwiftUI`. Would make use of `TextFIeld` binding and closure properties, integrated with `CurrencyFormatter` to format the text as currency, from right to left, with same behavior as on `CurrencyUITextFieldDelegate`:
**2.** Bridging a custom `UITextField` subclass via `UIViewRepresentable`, that would receive a `CurrencyFormatter`, and use a customizable `CurrencyUITextFieldDelegate` internally.

I'm confident **1** will work, but further tests must be done to ensure correct behavior. If anything goes south it should be easy and fine to re-route to option **2**.
Besides **1** being vanilla SwiftUI, it would also be smaller in size, complexity, and non dependent on `UIKit`. Let's see how it goes 🤞 .
