### ISSUE TITLE
Bug: Modifying state during view update, this will cause undefined behavior.

### ISSUE THREAD

**Issue by gusadi09** [marinofelipe/CurrencyText#84]
<img width="409" alt="Jepretan Layar 2021-10-27 pukul 22 55 52" src="https://user-images.githubusercontent.com/49934033/139091691-26a5ab18-678c-4615-8fc9-6212d61a87ed.png">
i found this bug while running a currency text field, and make a navigation link delayed

**Comment by marinofelipe** [comment]
@gusadi09 I'm closing this one, let me know if you need any help with it.
