### ISSUE TITLE
SwiftUI view not updated when currency value changed

### ISSUE THREAD

**Issue by naoisegolden** [marinofelipe/CurrencyText#87]
## What problems I want to solve?
If the `CurrencyFormatter` `currency` value is changed and re-rendered, the `CurrencyTextField` does not update with the new currency value.

Example:
```swift
struct SomeView: View {
    @State var currency: String
    @State var text: String
    @State var unformatted: String?
    @State var input: Double?
    
    var body: some View {
        Picker("Currency", selection: $currency) {
            ForEach(["EUR", "GBP", "USD"], id: \.self) { currency in
                Text(currency)
            }
        }
        CurrencyTextField(
            configuration: .init(
                placeholder: "0",
                text: $text,
                unformattedText: $unformatted,
                inputAmount: $input,
                formatter: CurrencyFormatter {
                    // HERE the View is not updated when `$currency` changes
                    $0.currency = Currency(rawValue: currency)!
                },
                textFieldConfiguration: { uiTextField in
                    // …
                }
            )
        )
    }
}
```

![change-currency-dynamically](https://user-images.githubusercontent.com/250892/171053392-99764d92-322e-4993-9131-b9adc66e749b.gif)

## What value it delivers?
It would allow to dynamically change the currency of the `CurrencyTextField`

## Tasks
TBD

## Dependecies / References
No dependencies and/or references by now.

**Comment by marinofelipe** [comment]
Hi @naoisegolden, thanks for the issue :).

I was able to reproduce it here.
This is a good finding, and I can say it's mostly because on `UIKit`, updating a formatter as a reference type would do the work, while on `SwiftUI`, via `UIViewRepresentable`, the `updateUIView` function should be ensuring such update is propagated.

I'll work on a patch and will get back to you whenever it's ready to be tested and hopefully released.

Cheers!

**Comment by leafarenuk** [comment]
@marinofelipe looking forward to the patch because I'm stuck at the same point as @naoisegolden 🤷🏼‍♂️

**Comment by marinofelipe** [comment]
Hey @leafarenuk and @naoisegolden, 

Could you please check if [2.3.1](https://github.com/marinofelipe/CurrencyText/releases/tag/2.3.1) has the issue fixed?
Thank you!

**Comment by leafarenuk** [comment]
> 

thanks for the fast fix! It's working in my use case! ✅

**Comment by marinofelipe** [comment]
Hi @leafarenuk , thanks for the report. Yeah, it seems the solution did not cover all scenarios.
I'll work in another fix, and hopefully will have it fully working soon.

**Comment by marinofelipe** [comment]
Hey @leafarenuk , thanks for the report.
I will work on make it fully work and will hopefully have it ready soon.

**Comment by marinofelipe** [comment]
Here is a sneak peak on the update/fix I'm doing:

https://user-images.githubusercontent.com/18131704/172071226-30c9c391-f099-4158-91a3-237826218ec4.mp4

We'll run few more tests before making it an official version, but it's looking promising 🤞 .
The only con is that it will require a breaking change, though it will be a very small and worth one - making the formatter a binding so it propagates the updates.

**Comment by marinofelipe** [comment]
Hey @leafarenuk and @naoisegolden.

I finally found some time to wrap it up. Could you please try out the draft release [3.0.0](https://github.com/marinofelipe/CurrencyText/releases/tag/3.0.0)?

Thanks :), and hopefully it will be fully working this time ;). Let me know in case you face any issues.

**Comment by leafarenuk** [comment]
> Hey @leafarenuk and @naoisegolden.
> 
> I finally found some time to wrap it up. Could you please try out the draft release [3.0.0](https://github.com/marinofelipe/CurrencyText/releases/tag/3.0.0)?
> 
> Thanks :), and hopefully it will be fully working this time ;). Let me know in case you face any issues.

thanks @marinofelipe. its working in my use case now including the switch between currencies and the auto update of the currency field 💪🏼

**Comment by marinofelipe** [comment]
Thank you @leafarenuk !!
