### ISSUE TITLE
I can`t input optional floating point

### ISSUE THREAD

**Issue by Shohjahont9** [marinofelipe/CurrencyText#93]
## I can`t input optional floating point?
Actually, I want to input $10 instead of $10.0 and I have to add a floating point anytime. Now if I click 1, it starts from 0.1, then I should click 0 to get $1.0

**Comment by marinofelipe** [comment]
Hi @Shohjahont9 

> Actually, I want to input $10 instead of $10.0 and I have to add a floating point anytime
To input `$10` the formatter can be configured with `hasDecimals` as `false`, and then changed to `true` at any point you'd like to input decimals, ie

```
the value is $10
// hasDecimals is changed to true
the user types 50
the value is changed to $10,50
```

Have you tried that? I'm not sure though the UX would be great. Currency text wasn't designed with decimal being optionally inputed at any time

**Comment by marinofelipe** [comment]
Hi @Shohjahont9 , I'm closing it for now, but feel free to reopen it in case you have any follow ups 🙇
